[project]
name = "ai-librarian-frontend"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.7.2",
    "httpx>=0.28.1",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"
